baseurl: "https://f-df.com/"
languageCode: "zh-cn"
title: "冯冬发"
theme: "hugo-xmin"
googleAnalytics: "G-SZ6DTC5YCR"
disqusShortname: "home-yuerdzhipi"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  post: "/post/:slug/"

menu:
  main:
    - name: 首页
      url: ""
      weight: 1
    - name: 博文
      url: "/post/"
      weight: 2
    - name: 分类
      url: "/categories/"
      weight: 3
    - name: 标签
      url: "/tags/"
      weight: 4
    - name: 简历
      url: "/cv/"
      weight: 5
    - name: 订阅
      url: "/index.xml"
      weight: 6

params:
  description: "Feng dongfa's personal website built through Hugo and blogdown."
  footer: "&copy; [Dongfa Feng](https://f-df.com) 2021 -- 2021 | [Bilibili](https://space.bilibili.com/40240481) | [Gitee](https://gitee.com/super401) | [Github](https://github.com/fengdongfa1995) | [Mail](mailto:fengdongfa1995@163.com) | [Zhihu](https://www.zhihu.com/people/im401)"

markup:
  goldmark:
    renderer:
      unsafe: true
